### PR TITLE
Add inheritance ordering checks

### PR DESCRIPTION
**Pull request by ernestognw**

### CODE REVIEW

**Comment by ernestognw** [comment]
Merging after discussing internally. We think this covers enough compatibility with OpenZeppelin Contracts since it already imports the relevant contracts.

**Review by Amxx — APPROVED** [review]
We'll need to improve it to add all of the main repo into the ordering, but that is a good start

**Comment by Amxx** [comment]
Here the relevant are governor. It is currently not imported :/

**Comment by ernestognw** [comment]
Yes. I added this to our 2025 wishlist

**Pull request merged**
